// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBMFUOq6QssSxefbojyhVF_lEHfI6UMlQ',
    appId: '1:580280550730:web:4ca111596bfb05676aadb3',
    messagingSenderId: '580280550730',
    projectId: 'folderredirectionmacabenta',
    authDomain: 'folderredirectionmacabenta.firebaseapp.com',
    storageBucket: 'folderredirectionmacabenta.firebasestorage.app',
    measurementId: 'G-T1QBPYCCP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARtPoN17HmEkcS_QuRdB2atWnOx-YkeAM',
    appId: '1:580280550730:android:973a80cefca552176aadb3',
    messagingSenderId: '580280550730',
    projectId: 'folderredirectionmacabenta',
    storageBucket: 'folderredirectionmacabenta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe0aolpdDrXk3tjYs1U50lHRPZwpPmkjQ',
    appId: '1:580280550730:ios:6e922119b19db4e26aadb3',
    messagingSenderId: '580280550730',
    projectId: 'folderredirectionmacabenta',
    storageBucket: 'folderredirectionmacabenta.firebasestorage.app',
    iosBundleId: 'com.example.siaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe0aolpdDrXk3tjYs1U50lHRPZwpPmkjQ',
    appId: '1:580280550730:ios:6e922119b19db4e26aadb3',
    messagingSenderId: '580280550730',
    projectId: 'folderredirectionmacabenta',
    storageBucket: 'folderredirectionmacabenta.firebasestorage.app',
    iosBundleId: 'com.example.siaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBMFUOq6QssSxefbojyhVF_lEHfI6UMlQ',
    appId: '1:580280550730:web:2ddf11e422d147426aadb3',
    messagingSenderId: '580280550730',
    projectId: 'folderredirectionmacabenta',
    authDomain: 'folderredirectionmacabenta.firebaseapp.com',
    storageBucket: 'folderredirectionmacabenta.firebasestorage.app',
    measurementId: 'G-SRPW13GRQ1',
  );
}
